= ESH – Embedded SHell
:script-name: esh
:script-sha1: f12b7b1d21bc0b091425bbbabe007691c79deada
:gh-name: jirutka/{script-name}
:version: 0.1.0

ifdef::env-github[]
image:https://travis-ci.org/{gh-name}.svg?branch=master["Build Status", link="https://travis-ci.org/{gh-name}"]
endif::env-github[]

*esh* (embedded shell) is a templating engine for evaluating shell commands embedded in arbitrary templates.
It's like ERB (Embedded RuBy) for shell, intended to be used for templating configuration files.

esh is implemented in ~160 lines (LoC) of shell and awk.


== Requirements

* http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html[POSIX-sh] compatible shell (e.g. Busybox ash, dash, ZSH, bash, …)
* common Unix userland with `awk` and `sed` (e.g. from Busybox, GNU, …)


== Usage

Read man page link:{script-name}.1.adoc[{script-name}(1)].

You can add {script-name} as a submodule into your repository or download it on demand, e.g.:

[source, sh, subs="+attributes"]
wget https://raw.githubusercontent.com/{gh-name}/v{version}/{script-name} \
    && echo '{script-sha1}  {script-name}' | sha1sum -c \
    || exit 1


== Examples

[source, nginx]
----
http {
    access_log <%= $logs_dir/access.log %> main;

    resolver <%= $(sed -En 's/^nameserver ([^#]+)/\1/p' /etc/resolv.conf) %>;

    <% if nginx -V 2>&1 | grep -q lua-nginx-module; then -%>
    lua_package_path '<%= $(pkg-config --variable=INSTALL_LMOD lua) %>/?.lua';
    <% fi -%>

    <%# The rest of the config is omitted %>
}
----


== Credits

ESH template syntax is based on ERB (Embedded Ruby).

Tests and some concepts are inspired by https://github.com/jwilk/shellcat[shellcat].


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
