= ESH – Embedded SHell
:source-language: sh
:script-name: esh
:script-sha1: f0074522d43bf1c06bf2c9b26092f754b7c4fa19
:gh-name: jirutka/{script-name}
:version: 0.2.0

ifdef::env-github[]
image:https://travis-ci.org/{gh-name}.svg?branch=master["Build Status", link="https://travis-ci.org/{gh-name}"]
endif::env-github[]

*esh* (embedded shell) is a templating engine for evaluating shell commands embedded in arbitrary templates.
It’s like ERB (Embedded RuBy) for shell, intended to be used for templating configuration files.
Unlike ERB it provides support for including one ESH template into another (since version 0.2.0).

esh is implemented in ~290 lines (LoC) of shell and awk.


== Requirements

* http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html[POSIX-sh] compatible shell (e.g. Busybox ash, dash, ZSH, bash, …)
* common Unix userland with `awk` and `sed` (e.g. from Busybox, GNU, …)
* (https://github.com/asciidoctor/asciidoctor[Asciidoctor] to build a man page)


== Installation

=== Alpine Linux

Install package *{script-name}* from the Alpine’s community repository:

[source, subs="+attributes"]
apk add {script-name}

IMPORTANT: This package is in Alpine stable since v3.7. You can also install it from _edge_ (unstable) branch.


=== Fedora

[source, subs="+attributes"]
dnf install {script-name}


=== openSUSE

Install package *{script-name}* from https://build.opensuse.org/project/show/home:jirutka/[my repository] on https://build.opensuse.org[openSUSE Build Service]:

[source, subs="+attributes"]
zypper addrepo http://download.opensuse.org/repositories/home:jirutka/openSUSE_Leap_15.0/home:jirutka.repo
zypper refresh
zypper install {script-name}


=== On CI

You can add {script-name} as a submodule into your repository or download it on demand, e.g.:

[source, subs="+attributes"]
wget https://raw.githubusercontent.com/{gh-name}/v{version}/{script-name} \
    && echo '{script-sha1}  {script-name}' | sha1sum -c \
    || exit 1


=== Manually

. Download and unpack release tarball:
[source, subs="+attributes"]
wget https://github.com/{gh-name}/archive/v{version}/{script-name}-{version}.tar.gz
tar -xzf {script-name}-{version}.tar.gz
cd {script-name}-{version}

. Run tests:
[source]
make test

. Build a man page and install esh:
+
[source]
make install prefix=/usr/local DESTDIR=/
+
or just copy `esh` whether you want, it’s a plain shell script.


== Usage

Read man page link:{script-name}.1.adoc[{script-name}(1)].


== Examples

[source, nginx]
----
http {
    access_log <%= $logs_dir/access.log %> main;

    resolver <%= $(sed -En 's/^nameserver ([^#]+)/\1/p' /etc/resolv.conf) %>;

    <% if nginx -V 2>&1 | grep -q lua-nginx-module; then -%>
    lua_package_path '<%= $(pkg-config --variable=INSTALL_LMOD lua) %>/?.lua';
    <% fi -%>

    <%+ ./http-common.esh %>

    <%# The rest of the config is omitted %>
}
----


== Credits

ESH template syntax is based on ERB (Embedded Ruby).

Tests and some concepts are inspired by https://github.com/jwilk/shellcat[shellcat].


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
