#!/bin/sh
# vim: set ts=4:
set -eu

: ${TEST_NAME:=${1:-}}

if [ -z "$TEST_NAME" ]; then
	echo "Usage: $0 TEST_NAME" >&2; exit 1
fi

${ESH:-esh} "$TEST_NAME.in" > "$TEST_NAME.err"
diff -uU 999 -L "$TEST_NAME.exp" -L "$TEST_NAME.err" \
	"$TEST_NAME.exp" "$TEST_NAME.err"
